# Generated by Django 5.2.9 on 2025-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="Unknown User", max_length=150),
            preserve_default=False,
        ),
    ]
