# Generated by Django 5.2.9 on 2026-03-30 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Unique username for profile",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number with country code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="GitHub profile URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        help_text="Twitter/X profile URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "leetcode_url",
                    models.URLField(
                        blank=True,
                        help_text="LeetCode profile URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True,
                        help_text="Education details in JSON format",
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short bio about the user",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Skills in JSON format", null=True
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True,
                        help_text="Work experience in JSON format",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Current location",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="Personal website URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
